/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StudentsTable: typeof import('./components/StudentsTable.vue')['default']
  }
}
